// Code generated by '$ tables/generator/file_go'. DO NOT EDIT.

package tables

import (
	"microlog/tables/table_data"
	"microlog/tables/table_instances"
	"microlog/tables/table_paths"
	"microlog/tables/table_status"
	"microlog/tables/table_stream"
	"microlog/tables/table_timeline"
	"testing"
)

// // // // // // // //

func TestData(t *testing.T) {
	if table_data.Table != "data" {
		t.Error("table name should be empty")
	}
}

func TestInstances(t *testing.T) {
	if table_instances.Table != "instances" {
		t.Error("table name should be empty")
	}
}

func TestPaths(t *testing.T) {
	if table_paths.Table != "paths" {
		t.Error("table name should be empty")
	}
}

func TestStatus(t *testing.T) {
	if table_status.Table != "status" {
		t.Error("table name should be empty")
	}
}

func TestStream(t *testing.T) {
	if table_stream.Table != "stream" {
		t.Error("table name should be empty")
	}
}

func TestTimeline(t *testing.T) {
	if table_timeline.Table != "timeline" {
		t.Error("table name should be empty")
	}
}
