name: Go Tests and Benchmarks
# Original source: https://github.com/Bookshelf-Writer/scripts-for-integration/blob/main/workflows/Test-Go.yml

on:
  pull_request:
    paths-ignore:
      - '*.txt'
      - '*.md'
      - '*.sh'
  push:
    tags-ignore:
      - '*'

jobs:
  generate:
    name: "Generate"
    runs-on: ubuntu-latest
    if: "!contains(github.event_name, 'release')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ${{ runner.os == 'Windows' && 'C:\Users\runneradmin\go\pkg\mod' || '~/go/pkg/mod' }}
            ${{ runner.os == 'Windows' && 'C:\Users\runneradmin\go\bin' || '~/go/bin' }}
            go.sum
          key: ${{ runner.os }}-go-${{ hashFiles('go.mod') }}
          restore-keys: ${{ runner.os }}-go

      - name: Run go generate
        run: |
          go mod tidy
          go generate ./...

      - name: Upload updated repository as artifact
        uses: actions/upload-artifact@v4
        with:
          name: updated-repo
          path: .

  test:
    name: "Test and Benchmark [${{ matrix.os }}]"
    needs: generate
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event_name, 'release')"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        go-version: [ 1.24 ]
    permissions:
      contents: write

    steps:
      - name: Download updated repository
        uses: actions/download-artifact@v4
        with:
          name: updated-repo
          path: .

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ${{ runner.os == 'Windows' && 'C:\Users\runneradmin\go\pkg\mod' || '~/go/pkg/mod' }}
            ${{ runner.os == 'Windows' && 'C:\Users\runneradmin\go\bin' || '~/go/bin' }}
            go.sum
          key: ${{ runner.os }}-go-${{ hashFiles('go.mod') }}
          restore-keys: ${{ runner.os }}-go

      - name: Run tests
        run: go test -v ./... || exit 1

      - name: Run benchmarks
        run: go test -bench . -v ./... || exit 1